### ISSUE TITLE
Can't install opkg on v3.x

### ISSUE THREAD

**Issue by Camouflager** [Jayy001/RmKeyboard#2]
Could you give any hint on how did you make opkg work on Rm v3.x?
I tried installing  tolvec on my Rm1 and it crashed with the wget

**Comment by Eeems** [comment]
> Could you give any hint on how did you make opkg work on Rm v3.x? I tried installing tolvec on my Rm1 and it crashed with the wget

Please do not ignore warnings when following instructions. Toltec does not support 3.x currently as outlined by the large warning before the installation instructions.

https://remarkable.guide/faqs.html#can-i-install-toltec-on-my-os-version
https://remarkable.guide/faqs.html#can-i-install-toltec-before-my-os-version-is-supported
https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version

**Comment by Camouflager** [comment]
Yeah… tried it on 3.3.x. Turns out my rm1 doesn’t have uinput so server fails on importing it
